apiVersion: apps/v1
kind: Deployment
metadata:
  name: healthcare-k8s-deployment
spec:
  replicas: 2
  selector:
    matchLabels:
      app: healthcare-k8s
  template:
    metadata:
      labels:
        app: healthcare-k8s
    spec:
      containers:
        - name: healthcare-k8s
          image: shreejitnair2000/staragileprojecthealthcare:v1
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
---

apiVersion: v1
kind: Service
metadata:
  name: healthcare-k8ssvc
spec:
  selector:
    app: healthcare-k8s
  type: NodePort
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
      nodePort: 31064  # Optional: matches what was assigned earlier
